// Code generated by wiresmith. DO NOT EDIT.
// source: resource/v1/resource.proto

package v1

import (
	"fmt"
	"github.com/gogo/protobuf/proto"
	commonv1 "github.com/grafana/tempo/pkg/tempopb/common/v1"
	"github.com/grafana/tempo/pkg/tempopb/protohelpers"
	"google.golang.org/protobuf/encoding/protowire"
	"io"
)

// Resource information.
type Resource struct {
	// Set of attributes that describe the resource.
	// Attribute keys MUST be unique (it is not allowed to have more than one
	// attribute with the same key).
	Attributes []commonv1.KeyValue `protobuf:"bytes,1,rep,name=attributes,proto3" json:"attributes,omitempty"`
	// dropped_attributes_count is the number of dropped attributes. If the value is 0, then
	// no attributes were dropped.
	DroppedAttributesCount uint32 `protobuf:"varint,2,opt,name=dropped_attributes_count,json=droppedAttributesCount,proto3" json:"droppedAttributesCount,omitempty"`

	XXX_fieldsPresent [1]uint64
}

func (m *Resource) Reset()      { *m = Resource{} }
func (*Resource) ProtoMessage() {}
func (m *Resource) String() string {
	if m == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *Resource) HasDroppedAttributesCount() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<0) != 0
}

func (m *Resource) GetAttributes() []commonv1.KeyValue {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Resource) GetDroppedAttributesCount() uint32 {
	if m != nil {
		return m.DroppedAttributesCount
	}
	return 0
}

func (m *Resource) Size() int {
	var n int
	for i := range m.Attributes {
		s := m.Attributes[i].Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	if m.DroppedAttributesCount != 0 {
		n += 1 + protowire.SizeVarint(uint64(m.DroppedAttributesCount))
	}
	return n
}

func (m *Resource) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Resource) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Resource) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.DroppedAttributesCount != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.DroppedAttributesCount))
		i--
		dAtA[i] = 0x10
	}
	for iNdEx := len(m.Attributes) - 1; iNdEx >= 0; iNdEx-- {
		size, err := m.Attributes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

const maxUnmarshalDepth = 10000

func skipValue(dAtA []byte, wireType int, fieldNum int32) (int, error) {
	iNdEx := 0
	l := len(dAtA)
	switch wireType {
	case 0:
		for shift := 0; ; shift++ {
			if shift >= 10 {
				return 0, fmt.Errorf("invalid varint")
			}
			if iNdEx >= l {
				return 0, fmt.Errorf("invalid varint")
			}
			iNdEx++
			if dAtA[iNdEx-1] < 0x80 {
				break
			}
		}
	case 1:
		if (iNdEx + 8) > l {
			return 0, fmt.Errorf("truncated fixed64")
		}
		iNdEx += 8
	case 2:
		var length uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, fmt.Errorf("invalid bytes")
			}
			if iNdEx >= l {
				return 0, fmt.Errorf("invalid bytes")
			}
			b := dAtA[iNdEx]
			iNdEx++
			length |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		if int(length) < 0 {
			return 0, fmt.Errorf("invalid bytes")
		}
		iNdEx += int(length)
		if iNdEx < 0 || iNdEx > l {
			return 0, fmt.Errorf("invalid bytes")
		}
	case 3:
		_, n := protowire.ConsumeGroup(protowire.Number(fieldNum), dAtA[iNdEx:])
		if n < 0 {
			return 0, fmt.Errorf("invalid group")
		}
		iNdEx += n
	case 5:
		if (iNdEx + 4) > l {
			return 0, fmt.Errorf("truncated fixed32")
		}
		iNdEx += 4
	default:
		return 0, fmt.Errorf("unknown wire type %d", wireType)
	}
	return iNdEx, nil
}

func (m *Resource) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *Resource) unmarshal(dAtA []byte, depth int) error {
	if depth > maxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	if l >= 256 {
		var preIdx int
		var field1count int
		for preIdx < l {
			var preWire uint64
			for shift := uint(0); ; shift += 7 {
				if preIdx >= l {
					break
				}
				b := dAtA[preIdx]
				preIdx++
				preWire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			preNum := int32(preWire >> 3)
			preTyp := int(preWire & 0x7)
			switch preNum {
			case 1:
				field1count++
			}
			switch preTyp {
			case 0:
				for preIdx < l {
					preIdx++
					if dAtA[preIdx-1] < 0x80 {
						break
					}
				}
			case 1:
				preIdx += 8
			case 2:
				var preLen uint64
				for shift := uint(0); ; shift += 7 {
					if preIdx >= l {
						break
					}
					b := dAtA[preIdx]
					preIdx++
					preLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				preIdx += int(preLen)
			case 5:
				preIdx += 4
			default:
				break
			}
			if preIdx < 0 || preIdx > l {
				break
			}
		}
		if field1count > 0 {
			m.Attributes = make([]commonv1.KeyValue, 0, field1count)
		}
	}
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 35 {
				return fmt.Errorf("proto: integer overflow")
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // attributes
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intByteLen := int(byteLen)
			if intByteLen < 0 {
				return fmt.Errorf("proto: negative length")
			}
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attributes = append(m.Attributes, commonv1.KeyValue{})
			if err := m.Attributes[len(m.Attributes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2: // dropped_attributes_count
			if wireType != 0 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DroppedAttributesCount = uint32(v)
			m.XXX_fieldsPresent[0] |= 1 << 0
		default:
			n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (this *Resource) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Resource)
	if !ok {
		that2, ok := that.(Resource)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.Attributes) != len(that1.Attributes) {
		return false
	}
	for i := range this.Attributes {
		if !this.Attributes[i].Equal(that1.Attributes[i]) {
			return false
		}
	}
	if this.DroppedAttributesCount != that1.DroppedAttributesCount {
		return false
	}
	return true
}

func (m *Resource) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *Resource) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

func (m *Resource) XXX_Merge(src proto.Message) {
	if s, ok := src.(*Resource); ok {
		b, err := s.Marshal()
		if err != nil {
			return
		}
		_ = m.Unmarshal(b)
	}
}

func (m *Resource) XXX_Size() int {
	return m.Size()
}

func (m *Resource) XXX_DiscardUnknown() {}

func (m *Resource) XXX_MessageName() string {
	return "tempopb.resource.v1.Resource"
}

func init() {
	protohelpers.RegisterType((*Resource)(nil), "tempopb.resource.v1.Resource")
}
