// Code generated by wiresmith. DO NOT EDIT.
// source: trace/v1/trace.proto

package v1

import (
	"bytes"
	"encoding/binary"
	"encoding/json"
	"fmt"
	"github.com/gogo/protobuf/proto"
	commonv1 "github.com/grafana/tempo/pkg/tempopb/common/v1"
	"github.com/grafana/tempo/pkg/tempopb/protohelpers"
	resourcev1 "github.com/grafana/tempo/pkg/tempopb/resource/v1"
	"google.golang.org/protobuf/encoding/protowire"
	"io"
	"strconv"
)

// SpanFlags represents constants used to interpret the
// Span.flags field, which is protobuf 'fixed32' type and is to
// be used as bit-fields. Each non-zero value defined in this enum is
// a bit-mask.  To extract the bit-field, for example, use an
// expression like:
//
// (span.flags & SPAN_FLAGS_TRACE_FLAGS_MASK)
//
// See https://www.w3.org/TR/trace-context-2/#trace-flags for the flag definitions.
//
// Note that Span flags were introduced in version 1.1 of the
// OpenTelemetry protocol.  Older Span producers do not set this
// field, consequently consumers should not rely on the absence of a
// particular flag bit to indicate the presence of a particular feature.
type SpanFlags int32

const (
	// The zero value for the enum. Should not be used for comparisons.
	// Instead use bitwise "and" with the appropriate mask as shown above.
	SPAN_FLAGS_DO_NOT_USE SpanFlags = 0
	// Bits 0-7 are used for trace flags.
	SPAN_FLAGS_TRACE_FLAGS_MASK SpanFlags = 255
	// Bits 8 and 9 are used to indicate that the parent span or link span is remote.
	// Bit 8 (`HAS_IS_REMOTE`) indicates whether the value is known.
	// Bit 9 (`IS_REMOTE`) indicates whether the span or link is remote.
	SPAN_FLAGS_CONTEXT_HAS_IS_REMOTE_MASK SpanFlags = 256
	SPAN_FLAGS_CONTEXT_IS_REMOTE_MASK     SpanFlags = 512
)

var SpanFlags_name = map[int32]string{
	0:   "SPAN_FLAGS_DO_NOT_USE",
	255: "SPAN_FLAGS_TRACE_FLAGS_MASK",
	256: "SPAN_FLAGS_CONTEXT_HAS_IS_REMOTE_MASK",
	512: "SPAN_FLAGS_CONTEXT_IS_REMOTE_MASK",
}

var SpanFlags_value = map[string]int32{
	"SPAN_FLAGS_DO_NOT_USE":                 0,
	"SPAN_FLAGS_TRACE_FLAGS_MASK":           255,
	"SPAN_FLAGS_CONTEXT_HAS_IS_REMOTE_MASK": 256,
	"SPAN_FLAGS_CONTEXT_IS_REMOTE_MASK":     512,
}

func (x SpanFlags) String() string {
	if name, ok := SpanFlags_name[int32(x)]; ok {
		return name
	}
	return strconv.FormatInt(int64(x), 10)
}

func (x *SpanFlags) UnmarshalJSON(data []byte) error {
	if len(data) > 0 && data[0] == '"' {
		var s string
		if err := json.Unmarshal(data, &s); err != nil {
			return err
		}
		if v, ok := SpanFlags_value[s]; ok {
			*x = SpanFlags(v)
			return nil
		}
		return fmt.Errorf("unknown enum value %q for SpanFlags", s)
	}
	var v int32
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	*x = SpanFlags(v)
	return nil
}

func (x SpanFlags) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}

// SpanKind is the type of span. Can be used to specify additional relationships between spans
// in addition to a parent/child relationship.
type Span_SpanKind int32

const (
	// Unspecified. Do NOT use as default.
	// Implementations MAY assume SpanKind to be INTERNAL when receiving UNSPECIFIED.
	Span_SPAN_KIND_UNSPECIFIED Span_SpanKind = 0
	// Indicates that the span represents an internal operation within an application,
	// as opposed to an operation happening at the boundaries. Default value.
	Span_SPAN_KIND_INTERNAL Span_SpanKind = 1
	// Indicates that the span covers server-side handling of an RPC or other
	// remote network request.
	Span_SPAN_KIND_SERVER Span_SpanKind = 2
	// Indicates that the span describes a request to some remote service.
	Span_SPAN_KIND_CLIENT Span_SpanKind = 3
	// Indicates that the span describes a producer sending a message to a broker.
	// Unlike CLIENT and SERVER, there is often no direct critical path latency relationship
	// between producer and consumer spans. A PRODUCER span ends when the message was accepted
	// by the broker while the logical processing of the message might span a much longer time.
	Span_SPAN_KIND_PRODUCER Span_SpanKind = 4
	// Indicates that the span describes consumer receiving a message from a broker.
	// Like the PRODUCER kind, there is often no direct critical path latency relationship
	// between producer and consumer spans.
	Span_SPAN_KIND_CONSUMER Span_SpanKind = 5
)

var Span_SpanKind_name = map[int32]string{
	0: "SPAN_KIND_UNSPECIFIED",
	1: "SPAN_KIND_INTERNAL",
	2: "SPAN_KIND_SERVER",
	3: "SPAN_KIND_CLIENT",
	4: "SPAN_KIND_PRODUCER",
	5: "SPAN_KIND_CONSUMER",
}

var Span_SpanKind_value = map[string]int32{
	"SPAN_KIND_UNSPECIFIED": 0,
	"SPAN_KIND_INTERNAL":    1,
	"SPAN_KIND_SERVER":      2,
	"SPAN_KIND_CLIENT":      3,
	"SPAN_KIND_PRODUCER":    4,
	"SPAN_KIND_CONSUMER":    5,
}

func (x Span_SpanKind) String() string {
	if name, ok := Span_SpanKind_name[int32(x)]; ok {
		return name
	}
	return strconv.FormatInt(int64(x), 10)
}

func (x *Span_SpanKind) UnmarshalJSON(data []byte) error {
	if len(data) > 0 && data[0] == '"' {
		var s string
		if err := json.Unmarshal(data, &s); err != nil {
			return err
		}
		if v, ok := Span_SpanKind_value[s]; ok {
			*x = Span_SpanKind(v)
			return nil
		}
		return fmt.Errorf("unknown enum value %q for Span_SpanKind", s)
	}
	var v int32
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	*x = Span_SpanKind(v)
	return nil
}

func (x Span_SpanKind) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}

// For the semantics of status codes see
// https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#set-status
type Status_StatusCode int32

const (
	// The default status.
	Status_STATUS_CODE_UNSET Status_StatusCode = 0
	// The Span has been validated by an Application developer or Operator to
	// have completed successfully.
	Status_STATUS_CODE_OK Status_StatusCode = 1
	// The Span contains an error.
	Status_STATUS_CODE_ERROR Status_StatusCode = 2
)

var Status_StatusCode_name = map[int32]string{
	0: "STATUS_CODE_UNSET",
	1: "STATUS_CODE_OK",
	2: "STATUS_CODE_ERROR",
}

var Status_StatusCode_value = map[string]int32{
	"STATUS_CODE_UNSET": 0,
	"STATUS_CODE_OK":    1,
	"STATUS_CODE_ERROR": 2,
}

func (x Status_StatusCode) String() string {
	if name, ok := Status_StatusCode_name[int32(x)]; ok {
		return name
	}
	return strconv.FormatInt(int64(x), 10)
}

func (x *Status_StatusCode) UnmarshalJSON(data []byte) error {
	if len(data) > 0 && data[0] == '"' {
		var s string
		if err := json.Unmarshal(data, &s); err != nil {
			return err
		}
		if v, ok := Status_StatusCode_value[s]; ok {
			*x = Status_StatusCode(v)
			return nil
		}
		return fmt.Errorf("unknown enum value %q for Status_StatusCode", s)
	}
	var v int32
	if err := json.Unmarshal(data, &v); err != nil {
		return err
	}
	*x = Status_StatusCode(v)
	return nil
}

func (x Status_StatusCode) MarshalJSON() ([]byte, error) {
	return json.Marshal(x.String())
}

// TracesData represents the traces data that can be stored in a persistent storage,
// OR can be embedded by other protocols that transfer OTLP traces data but do
// not implement the OTLP protocol.
//
// The main difference between this message and collector protocol is that
// in this message there will not be any "control" or "metadata" specific to
// OTLP protocol.
//
// When new fields are added into this message, the OTLP request MUST be updated
// as well.
type TracesData struct {
	// An array of ResourceSpans.
	// For data coming from a single resource this array will typically contain
	// one element. Intermediary nodes that receive data from multiple origins
	// typically batch the data before forwarding further and in that case this
	// array will contain multiple elements.
	ResourceSpans []ResourceSpans `protobuf:"bytes,1,rep,name=resource_spans,json=resourceSpans,proto3" json:"resourceSpans,omitempty"`
}

// A collection of ScopeSpans from a Resource.
type ResourceSpans struct {
	// The resource for the spans in this message.
	// If this field is not set then no resource info is known.
	Resource resourcev1.Resource `protobuf:"bytes,1,opt,name=resource,proto3" json:"resource,omitempty"`
	// A list of ScopeSpans that originate from a resource.
	ScopeSpans []ScopeSpans `protobuf:"bytes,2,rep,name=scope_spans,json=scopeSpans,proto3" json:"scopeSpans,omitempty"`
	// The Schema URL, if known. This is the identifier of the Schema that the resource data
	// is recorded in. To learn more about Schema URL see
	// https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
	// This schema_url applies to the data in the "resource" field. It does not apply
	// to the data in the "scope_spans" field which have their own schema_url field.
	SchemaUrl string `protobuf:"bytes,3,opt,name=schema_url,json=schemaUrl,proto3" json:"schemaUrl,omitempty"`

	XXX_fieldsPresent [1]uint64
}

// A collection of Spans produced by an InstrumentationScope.
type ScopeSpans struct {
	// The instrumentation scope information for the spans in this message.
	// Semantically when InstrumentationScope isn't set, it is equivalent with
	// an empty instrumentation scope name (unknown).
	Scope commonv1.InstrumentationScope `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// A list of Spans that originate from an instrumentation scope.
	Spans []Span `protobuf:"bytes,2,rep,name=spans,proto3" json:"spans,omitempty"`
	// The Schema URL, if known. This is the identifier of the Schema that the span data
	// is recorded in. To learn more about Schema URL see
	// https://opentelemetry.io/docs/specs/otel/schemas/#schema-url
	// This schema_url applies to all spans and span events in the "spans" field.
	SchemaUrl string `protobuf:"bytes,3,opt,name=schema_url,json=schemaUrl,proto3" json:"schemaUrl,omitempty"`

	XXX_fieldsPresent [1]uint64
}

// Event is a time-stamped annotation of the span, consisting of user-supplied
// text description and key-value pairs.
type Span_Event struct {
	// time_unix_nano is the time the event occurred.
	TimeUnixNano uint64 `protobuf:"fixed64,1,opt,name=time_unix_nano,json=timeUnixNano,proto3" json:"timeUnixNano,omitempty,string"`
	// name of the event.
	// This field is semantically required to be set to non-empty string.
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// attributes is a collection of attribute key/value pairs on the event.
	// Attribute keys MUST be unique (it is not allowed to have more than one
	// attribute with the same key).
	Attributes []commonv1.KeyValue `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty"`
	// dropped_attributes_count is the number of dropped attributes. If the value is 0,
	// then no attributes were dropped.
	DroppedAttributesCount uint32 `protobuf:"varint,4,opt,name=dropped_attributes_count,json=droppedAttributesCount,proto3" json:"droppedAttributesCount,omitempty"`

	XXX_fieldsPresent [1]uint64
}

// A pointer from the current span to another span in the same trace or in a
// different trace. For example, this can be used in batching operations,
// where a single batch handler processes multiple requests from different
// traces or when the handler receives a request from a different project.
type Span_Link struct {
	// A unique identifier of a trace that this linked span is part of. The ID is a
	// 16-byte array.
	TraceId []byte `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"traceId,omitempty"`
	// A unique identifier for the linked span. The ID is an 8-byte array.
	SpanId []byte `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"spanId,omitempty"`
	// The trace_state associated with the link.
	TraceState string `protobuf:"bytes,3,opt,name=trace_state,json=traceState,proto3" json:"traceState,omitempty"`
	// attributes is a collection of attribute key/value pairs on the link.
	// Attribute keys MUST be unique (it is not allowed to have more than one
	// attribute with the same key).
	Attributes []commonv1.KeyValue `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty"`
	// dropped_attributes_count is the number of dropped attributes. If the value is 0,
	// then no attributes were dropped.
	DroppedAttributesCount uint32 `protobuf:"varint,5,opt,name=dropped_attributes_count,json=droppedAttributesCount,proto3" json:"droppedAttributesCount,omitempty"`
	// Flags, a bit field.
	//
	// Bits 0-7 (8 least significant bits) are the trace flags as defined in W3C Trace
	// Context specification. To read the 8-bit W3C trace flag, use
	// `flags & SPAN_FLAGS_TRACE_FLAGS_MASK`.
	//
	// See https://www.w3.org/TR/trace-context-2/#trace-flags for the flag definitions.
	//
	// Bits 8 and 9 represent the 3 states of whether the link is remote.
	// The states are (unknown, is not remote, is remote).
	// To read whether the value is known, use `(flags & SPAN_FLAGS_CONTEXT_HAS_IS_REMOTE_MASK) != 0`.
	// To read whether the link is remote, use `(flags & SPAN_FLAGS_CONTEXT_IS_REMOTE_MASK) != 0`.
	//
	// Readers MUST NOT assume that bits 10-31 (22 most significant bits) will be zero.
	// When creating new spans, bits 10-31 (most-significant 22-bits) MUST be zero.
	//
	// [Optional].
	Flags uint32 `protobuf:"fixed32,6,opt,name=flags,proto3" json:"flags,omitempty"`

	XXX_fieldsPresent [1]uint64
}

// A Span represents a single operation performed by a single component of the system.
//
// The next available field id is 17.
type Span struct {
	// A unique identifier for a trace. All spans from the same trace share
	// the same `trace_id`. The ID is a 16-byte array. An ID with all zeroes OR
	// of length other than 16 bytes is considered invalid (empty string in OTLP/JSON
	// is zero-length and thus is also invalid).
	//
	// This field is required.
	TraceId []byte `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"traceId,omitempty"`
	// A unique identifier for a span within a trace, assigned when the span
	// is created. The ID is an 8-byte array. An ID with all zeroes OR of length
	// other than 8 bytes is considered invalid (empty string in OTLP/JSON
	// is zero-length and thus is also invalid).
	//
	// This field is required.
	SpanId []byte `protobuf:"bytes,2,opt,name=span_id,json=spanId,proto3" json:"spanId,omitempty"`
	// trace_state conveys information about request position in multiple distributed tracing graphs.
	// It is a trace_state in w3c-trace-context format: https://www.w3.org/TR/trace-context/#tracestate-header
	// See also https://github.com/w3c/distributed-tracing for more details about this field.
	TraceState string `protobuf:"bytes,3,opt,name=trace_state,json=traceState,proto3" json:"traceState,omitempty"`
	// The `span_id` of this span's parent span. If this is a root span, then this
	// field must be empty. The ID is an 8-byte array.
	ParentSpanId []byte `protobuf:"bytes,4,opt,name=parent_span_id,json=parentSpanId,proto3" json:"parentSpanId,omitempty"`
	// Flags, a bit field.
	//
	// Bits 0-7 (8 least significant bits) are the trace flags as defined in W3C Trace
	// Context specification. To read the 8-bit W3C trace flag, use
	// `flags & SPAN_FLAGS_TRACE_FLAGS_MASK`.
	//
	// See https://www.w3.org/TR/trace-context-2/#trace-flags for the flag definitions.
	//
	// Bits 8 and 9 represent the 3 states of whether a span's parent
	// is remote. The states are (unknown, is not remote, is remote).
	// To read whether the value is known, use `(flags & SPAN_FLAGS_CONTEXT_HAS_IS_REMOTE_MASK) != 0`.
	// To read whether the span is remote, use `(flags & SPAN_FLAGS_CONTEXT_IS_REMOTE_MASK) != 0`.
	//
	// When creating span messages, if the message is logically forwarded from another source
	// with an equivalent flags fields (i.e., usually another OTLP span message), the field SHOULD
	// be copied as-is. If creating from a source that does not have an equivalent flags field
	// (such as a runtime representation of an OpenTelemetry span), the high 22 bits MUST
	// be set to zero.
	// Readers MUST NOT assume that bits 10-31 (22 most significant bits) will be zero.
	//
	// [Optional].
	Flags uint32 `protobuf:"fixed32,16,opt,name=flags,proto3" json:"flags,omitempty"`
	// A description of the span's operation.
	//
	// For example, the name can be a qualified method name or a file name
	// and a line number where the operation is called. A best practice is to use
	// the same display name at the same call point in an application.
	// This makes it easier to correlate spans in different traces.
	//
	// This field is semantically required to be set to non-empty string.
	// Empty value is equivalent to an unknown span name.
	//
	// This field is required.
	Name string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	// Distinguishes between spans generated in a particular context. For example,
	// two spans with the same name may be distinguished using `CLIENT` (caller)
	// and `SERVER` (callee) to identify queueing latency associated with the span.
	Kind Span_SpanKind `protobuf:"varint,6,opt,name=kind,proto3,enum=tempopb.trace.v1.Span.SpanKind" json:"kind,omitempty"`
	// start_time_unix_nano is the start time of the span. On the client side, this is the time
	// kept by the local machine where the span execution starts. On the server side, this
	// is the time when the server's application handler starts running.
	// Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
	//
	// This field is semantically required and it is expected that end_time >= start_time.
	StartTimeUnixNano uint64 `protobuf:"fixed64,7,opt,name=start_time_unix_nano,json=startTimeUnixNano,proto3" json:"startTimeUnixNano,omitempty,string"`
	// end_time_unix_nano is the end time of the span. On the client side, this is the time
	// kept by the local machine where the span execution ends. On the server side, this
	// is the time when the server application handler stops running.
	// Value is UNIX Epoch time in nanoseconds since 00:00:00 UTC on 1 January 1970.
	//
	// This field is semantically required and it is expected that end_time >= start_time.
	EndTimeUnixNano uint64 `protobuf:"fixed64,8,opt,name=end_time_unix_nano,json=endTimeUnixNano,proto3" json:"endTimeUnixNano,omitempty,string"`
	// attributes is a collection of key/value pairs. Note, global attributes
	// like server name can be set using the resource API. Examples of attributes:
	//
	// "/http/user_agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36"
	// "/http/server_latency": 300
	// "example.com/myattribute": true
	// "example.com/score": 10.239
	//
	// The OpenTelemetry API specification further restricts the allowed value types:
	// https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/README.md#attribute
	// Attribute keys MUST be unique (it is not allowed to have more than one
	// attribute with the same key).
	Attributes []commonv1.KeyValue `protobuf:"bytes,9,rep,name=attributes,proto3" json:"attributes,omitempty"`
	// dropped_attributes_count is the number of attributes that were discarded. Attributes
	// can be discarded because their keys are too long or because there are too many
	// attributes. If this value is 0, then no attributes were dropped.
	DroppedAttributesCount uint32 `protobuf:"varint,10,opt,name=dropped_attributes_count,json=droppedAttributesCount,proto3" json:"droppedAttributesCount,omitempty"`
	// events is a collection of Event items.
	Events []Span_Event `protobuf:"bytes,11,rep,name=events,proto3" json:"events,omitempty"`
	// dropped_events_count is the number of dropped events. If the value is 0, then no
	// events were dropped.
	DroppedEventsCount uint32 `protobuf:"varint,12,opt,name=dropped_events_count,json=droppedEventsCount,proto3" json:"droppedEventsCount,omitempty"`
	// links is a collection of Links, which are references from this span to a span
	// in the same or different trace.
	Links []Span_Link `protobuf:"bytes,13,rep,name=links,proto3" json:"links,omitempty"`
	// dropped_links_count is the number of dropped links after the maximum size was
	// enforced. If this value is 0, then no links were dropped.
	DroppedLinksCount uint32 `protobuf:"varint,14,opt,name=dropped_links_count,json=droppedLinksCount,proto3" json:"droppedLinksCount,omitempty"`
	// An optional final status for this span. Semantically when Status isn't set, it means
	// span's status code is unset, i.e. assume STATUS_CODE_UNSET (code = 0).
	Status Status `protobuf:"bytes,15,opt,name=status,proto3" json:"status,omitempty"`

	XXX_fieldsPresent [1]uint64
}

// The Status type defines a logical error model that is suitable for different
// programming environments, including REST APIs and RPC APIs.
type Status struct {
	// A developer-facing human readable error message.
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	// The status code.
	Code Status_StatusCode `protobuf:"varint,3,opt,name=code,proto3,enum=tempopb.trace.v1.Status.StatusCode" json:"code,omitempty"`

	XXX_fieldsPresent [1]uint64
}

func (m *TracesData) Reset()      { *m = TracesData{} }
func (*TracesData) ProtoMessage() {}
func (m *TracesData) String() string {
	if m == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *ResourceSpans) Reset()      { *m = ResourceSpans{} }
func (*ResourceSpans) ProtoMessage() {}
func (m *ResourceSpans) String() string {
	if m == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *ScopeSpans) Reset()      { *m = ScopeSpans{} }
func (*ScopeSpans) ProtoMessage() {}
func (m *ScopeSpans) String() string {
	if m == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *Span_Event) Reset()      { *m = Span_Event{} }
func (*Span_Event) ProtoMessage() {}
func (m *Span_Event) String() string {
	if m == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *Span_Link) Reset()      { *m = Span_Link{} }
func (*Span_Link) ProtoMessage() {}
func (m *Span_Link) String() string {
	if m == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *Span) Reset()      { *m = Span{} }
func (*Span) ProtoMessage() {}
func (m *Span) String() string {
	if m == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *Status) Reset()      { *m = Status{} }
func (*Status) ProtoMessage() {}
func (m *Status) String() string {
	if m == nil {
		return "<nil>"
	}
	return fmt.Sprintf("%v", *m)
}

func (m *ResourceSpans) HasResource() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<0) != 0
}

func (m *ResourceSpans) HasSchemaUrl() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<1) != 0
}

func (m *ScopeSpans) HasScope() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<0) != 0
}

func (m *ScopeSpans) HasSchemaUrl() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<1) != 0
}

func (m *Span_Event) HasTimeUnixNano() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<0) != 0
}

func (m *Span_Event) HasName() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<1) != 0
}

func (m *Span_Event) HasDroppedAttributesCount() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<2) != 0
}

func (m *Span_Link) HasTraceId() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<0) != 0
}

func (m *Span_Link) HasSpanId() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<1) != 0
}

func (m *Span_Link) HasTraceState() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<2) != 0
}

func (m *Span_Link) HasDroppedAttributesCount() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<3) != 0
}

func (m *Span_Link) HasFlags() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<4) != 0
}

func (m *Span) HasTraceId() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<0) != 0
}

func (m *Span) HasSpanId() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<1) != 0
}

func (m *Span) HasTraceState() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<2) != 0
}

func (m *Span) HasParentSpanId() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<3) != 0
}

func (m *Span) HasFlags() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<4) != 0
}

func (m *Span) HasName() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<5) != 0
}

func (m *Span) HasKind() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<6) != 0
}

func (m *Span) HasStartTimeUnixNano() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<7) != 0
}

func (m *Span) HasEndTimeUnixNano() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<8) != 0
}

func (m *Span) HasDroppedAttributesCount() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<9) != 0
}

func (m *Span) HasDroppedEventsCount() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<10) != 0
}

func (m *Span) HasDroppedLinksCount() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<11) != 0
}

func (m *Span) HasStatus() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<12) != 0
}

func (m *Status) HasMessage() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<0) != 0
}

func (m *Status) HasCode() bool {
	if m == nil {
		return false
	}
	return m.XXX_fieldsPresent[0]&(1<<1) != 0
}

func (m *TracesData) GetResourceSpans() []ResourceSpans {
	if m != nil {
		return m.ResourceSpans
	}
	return nil
}

func (m *ResourceSpans) GetResource() *resourcev1.Resource {
	if m != nil {
		return &m.Resource
	}
	return nil
}

func (m *ResourceSpans) GetScopeSpans() []ScopeSpans {
	if m != nil {
		return m.ScopeSpans
	}
	return nil
}

func (m *ResourceSpans) GetSchemaUrl() string {
	if m != nil {
		return m.SchemaUrl
	}
	return ""
}

func (m *ScopeSpans) GetScope() *commonv1.InstrumentationScope {
	if m != nil {
		return &m.Scope
	}
	return nil
}

func (m *ScopeSpans) GetSpans() []Span {
	if m != nil {
		return m.Spans
	}
	return nil
}

func (m *ScopeSpans) GetSchemaUrl() string {
	if m != nil {
		return m.SchemaUrl
	}
	return ""
}

func (m *Span_Event) GetTimeUnixNano() uint64 {
	if m != nil {
		return m.TimeUnixNano
	}
	return 0
}

func (m *Span_Event) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Span_Event) GetAttributes() []commonv1.KeyValue {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Span_Event) GetDroppedAttributesCount() uint32 {
	if m != nil {
		return m.DroppedAttributesCount
	}
	return 0
}

func (m *Span_Link) GetTraceId() []byte {
	if m != nil {
		return m.TraceId
	}
	return nil
}

func (m *Span_Link) GetSpanId() []byte {
	if m != nil {
		return m.SpanId
	}
	return nil
}

func (m *Span_Link) GetTraceState() string {
	if m != nil {
		return m.TraceState
	}
	return ""
}

func (m *Span_Link) GetAttributes() []commonv1.KeyValue {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Span_Link) GetDroppedAttributesCount() uint32 {
	if m != nil {
		return m.DroppedAttributesCount
	}
	return 0
}

func (m *Span_Link) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *Span) GetTraceId() []byte {
	if m != nil {
		return m.TraceId
	}
	return nil
}

func (m *Span) GetSpanId() []byte {
	if m != nil {
		return m.SpanId
	}
	return nil
}

func (m *Span) GetTraceState() string {
	if m != nil {
		return m.TraceState
	}
	return ""
}

func (m *Span) GetParentSpanId() []byte {
	if m != nil {
		return m.ParentSpanId
	}
	return nil
}

func (m *Span) GetFlags() uint32 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *Span) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Span) GetKind() Span_SpanKind {
	if m != nil {
		return m.Kind
	}
	return 0
}

func (m *Span) GetStartTimeUnixNano() uint64 {
	if m != nil {
		return m.StartTimeUnixNano
	}
	return 0
}

func (m *Span) GetEndTimeUnixNano() uint64 {
	if m != nil {
		return m.EndTimeUnixNano
	}
	return 0
}

func (m *Span) GetAttributes() []commonv1.KeyValue {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *Span) GetDroppedAttributesCount() uint32 {
	if m != nil {
		return m.DroppedAttributesCount
	}
	return 0
}

func (m *Span) GetEvents() []Span_Event {
	if m != nil {
		return m.Events
	}
	return nil
}

func (m *Span) GetDroppedEventsCount() uint32 {
	if m != nil {
		return m.DroppedEventsCount
	}
	return 0
}

func (m *Span) GetLinks() []Span_Link {
	if m != nil {
		return m.Links
	}
	return nil
}

func (m *Span) GetDroppedLinksCount() uint32 {
	if m != nil {
		return m.DroppedLinksCount
	}
	return 0
}

func (m *Span) GetStatus() *Status {
	if m != nil {
		return &m.Status
	}
	return nil
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Status) GetCode() Status_StatusCode {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *TracesData) Size() int {
	var n int
	for i := range m.ResourceSpans {
		s := m.ResourceSpans[i].Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	return n
}

func (m *ResourceSpans) Size() int {
	var n int
	{
		s := m.Resource.Size()
		if s > 0 {
			n += 1 + protowire.SizeVarint(uint64(s)) + s
		} else if m.XXX_fieldsPresent[0]&(1<<0) != 0 {
			n += 2
		}
	}
	for i := range m.ScopeSpans {
		s := m.ScopeSpans[i].Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	if len(m.SchemaUrl) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.SchemaUrl))) + len(m.SchemaUrl)
	}
	return n
}

func (m *ScopeSpans) Size() int {
	var n int
	{
		s := m.Scope.Size()
		if s > 0 {
			n += 1 + protowire.SizeVarint(uint64(s)) + s
		} else if m.XXX_fieldsPresent[0]&(1<<0) != 0 {
			n += 2
		}
	}
	for i := range m.Spans {
		s := m.Spans[i].Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	if len(m.SchemaUrl) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.SchemaUrl))) + len(m.SchemaUrl)
	}
	return n
}

func (m *Span_Event) Size() int {
	var n int
	if m.TimeUnixNano != 0 {
		n += 9
	}
	if len(m.Name) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.Name))) + len(m.Name)
	}
	for i := range m.Attributes {
		s := m.Attributes[i].Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	if m.DroppedAttributesCount != 0 {
		n += 1 + protowire.SizeVarint(uint64(m.DroppedAttributesCount))
	}
	return n
}

func (m *Span_Link) Size() int {
	var n int
	if len(m.TraceId) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.TraceId))) + len(m.TraceId)
	}
	if len(m.SpanId) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.SpanId))) + len(m.SpanId)
	}
	if len(m.TraceState) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.TraceState))) + len(m.TraceState)
	}
	for i := range m.Attributes {
		s := m.Attributes[i].Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	if m.DroppedAttributesCount != 0 {
		n += 1 + protowire.SizeVarint(uint64(m.DroppedAttributesCount))
	}
	if m.Flags != 0 {
		n += 5
	}
	return n
}

func (m *Span) Size() int {
	var n int
	if len(m.TraceId) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.TraceId))) + len(m.TraceId)
	}
	if len(m.SpanId) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.SpanId))) + len(m.SpanId)
	}
	if len(m.TraceState) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.TraceState))) + len(m.TraceState)
	}
	if len(m.ParentSpanId) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.ParentSpanId))) + len(m.ParentSpanId)
	}
	if m.Flags != 0 {
		n += 6
	}
	if len(m.Name) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.Name))) + len(m.Name)
	}
	if m.Kind != 0 {
		n += 1 + protowire.SizeVarint(uint64(m.Kind))
	}
	if m.StartTimeUnixNano != 0 {
		n += 9
	}
	if m.EndTimeUnixNano != 0 {
		n += 9
	}
	for i := range m.Attributes {
		s := m.Attributes[i].Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	if m.DroppedAttributesCount != 0 {
		n += 1 + protowire.SizeVarint(uint64(m.DroppedAttributesCount))
	}
	for i := range m.Events {
		s := m.Events[i].Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	if m.DroppedEventsCount != 0 {
		n += 1 + protowire.SizeVarint(uint64(m.DroppedEventsCount))
	}
	for i := range m.Links {
		s := m.Links[i].Size()
		n += 1 + protowire.SizeVarint(uint64(s)) + s
	}
	if m.DroppedLinksCount != 0 {
		n += 1 + protowire.SizeVarint(uint64(m.DroppedLinksCount))
	}
	{
		s := m.Status.Size()
		if s > 0 {
			n += 1 + protowire.SizeVarint(uint64(s)) + s
		} else if m.XXX_fieldsPresent[0]&(1<<12) != 0 {
			n += 2
		}
	}
	return n
}

func (m *Status) Size() int {
	var n int
	if len(m.Message) > 0 {
		n += 1 + protowire.SizeVarint(uint64(len(m.Message))) + len(m.Message)
	}
	if m.Code != 0 {
		n += 1 + protowire.SizeVarint(uint64(m.Code))
	}
	return n
}

func (m *TracesData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *TracesData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *TracesData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	for iNdEx := len(m.ResourceSpans) - 1; iNdEx >= 0; iNdEx-- {
		size, err := m.ResourceSpans[iNdEx].MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

func (m *ResourceSpans) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ResourceSpans) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ResourceSpans) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if len(m.SchemaUrl) > 0 {
		i -= len(m.SchemaUrl)
		copy(dAtA[i:], m.SchemaUrl)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.SchemaUrl)))
		i--
		dAtA[i] = 0x1a
	}
	for iNdEx := len(m.ScopeSpans) - 1; iNdEx >= 0; iNdEx-- {
		size, err := m.ScopeSpans[iNdEx].MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Resource.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		if size > 0 {
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x0a
		} else if m.XXX_fieldsPresent[0]&(1<<0) != 0 {
			i--
			dAtA[i] = 0
			i--
			dAtA[i] = 0x0a
		}
	}
	return len(dAtA) - i, nil
}

func (m *ScopeSpans) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ScopeSpans) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ScopeSpans) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if len(m.SchemaUrl) > 0 {
		i -= len(m.SchemaUrl)
		copy(dAtA[i:], m.SchemaUrl)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.SchemaUrl)))
		i--
		dAtA[i] = 0x1a
	}
	for iNdEx := len(m.Spans) - 1; iNdEx >= 0; iNdEx-- {
		size, err := m.Spans[iNdEx].MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x12
	}
	{
		size, err := m.Scope.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		if size > 0 {
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x0a
		} else if m.XXX_fieldsPresent[0]&(1<<0) != 0 {
			i--
			dAtA[i] = 0
			i--
			dAtA[i] = 0x0a
		}
	}
	return len(dAtA) - i, nil
}

func (m *Span_Event) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Span_Event) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Span_Event) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.DroppedAttributesCount != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.DroppedAttributesCount))
		i--
		dAtA[i] = 0x20
	}
	for iNdEx := len(m.Attributes) - 1; iNdEx >= 0; iNdEx-- {
		size, err := m.Attributes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x12
	}
	if m.TimeUnixNano != 0 {
		i -= 8
		binary.LittleEndian.PutUint64(dAtA[i:], m.TimeUnixNano)
		i--
		dAtA[i] = 0x09
	}
	return len(dAtA) - i, nil
}

func (m *Span_Link) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Span_Link) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Span_Link) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Flags != 0 {
		i -= 4
		binary.LittleEndian.PutUint32(dAtA[i:], m.Flags)
		i--
		dAtA[i] = 0x35
	}
	if m.DroppedAttributesCount != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.DroppedAttributesCount))
		i--
		dAtA[i] = 0x28
	}
	for iNdEx := len(m.Attributes) - 1; iNdEx >= 0; iNdEx-- {
		size, err := m.Attributes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x22
	}
	if len(m.TraceState) > 0 {
		i -= len(m.TraceState)
		copy(dAtA[i:], m.TraceState)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.TraceState)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SpanId) > 0 {
		i -= len(m.SpanId)
		copy(dAtA[i:], m.SpanId)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.SpanId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TraceId) > 0 {
		i -= len(m.TraceId)
		copy(dAtA[i:], m.TraceId)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.TraceId)))
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

func (m *Span) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Span) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Span) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Flags != 0 {
		i -= 4
		binary.LittleEndian.PutUint32(dAtA[i:], m.Flags)
		i--
		dAtA[i] = 0x01
		i--
		dAtA[i] = 0x85
	}
	{
		size, err := m.Status.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		if size > 0 {
			i -= size
			i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
			i--
			dAtA[i] = 0x7a
		} else if m.XXX_fieldsPresent[0]&(1<<12) != 0 {
			i--
			dAtA[i] = 0
			i--
			dAtA[i] = 0x7a
		}
	}
	if m.DroppedLinksCount != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.DroppedLinksCount))
		i--
		dAtA[i] = 0x70
	}
	for iNdEx := len(m.Links) - 1; iNdEx >= 0; iNdEx-- {
		size, err := m.Links[iNdEx].MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x6a
	}
	if m.DroppedEventsCount != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.DroppedEventsCount))
		i--
		dAtA[i] = 0x60
	}
	for iNdEx := len(m.Events) - 1; iNdEx >= 0; iNdEx-- {
		size, err := m.Events[iNdEx].MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x5a
	}
	if m.DroppedAttributesCount != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.DroppedAttributesCount))
		i--
		dAtA[i] = 0x50
	}
	for iNdEx := len(m.Attributes) - 1; iNdEx >= 0; iNdEx-- {
		size, err := m.Attributes[iNdEx].MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = protohelpers.EncodeVarint(dAtA, i, uint64(size))
		i--
		dAtA[i] = 0x4a
	}
	if m.EndTimeUnixNano != 0 {
		i -= 8
		binary.LittleEndian.PutUint64(dAtA[i:], m.EndTimeUnixNano)
		i--
		dAtA[i] = 0x41
	}
	if m.StartTimeUnixNano != 0 {
		i -= 8
		binary.LittleEndian.PutUint64(dAtA[i:], m.StartTimeUnixNano)
		i--
		dAtA[i] = 0x39
	}
	if m.Kind != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.Kind))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Name) > 0 {
		i -= len(m.Name)
		copy(dAtA[i:], m.Name)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Name)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.ParentSpanId) > 0 {
		i -= len(m.ParentSpanId)
		copy(dAtA[i:], m.ParentSpanId)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.ParentSpanId)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.TraceState) > 0 {
		i -= len(m.TraceState)
		copy(dAtA[i:], m.TraceState)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.TraceState)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SpanId) > 0 {
		i -= len(m.SpanId)
		copy(dAtA[i:], m.SpanId)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.SpanId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TraceId) > 0 {
		i -= len(m.TraceId)
		copy(dAtA[i:], m.TraceId)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.TraceId)))
		i--
		dAtA[i] = 0x0a
	}
	return len(dAtA) - i, nil
}

func (m *Status) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	if size == 0 {
		return dAtA, nil
	}
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Status) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Status) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	if m.Code != 0 {
		i = protohelpers.EncodeVarint(dAtA, i, uint64(m.Code))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = protohelpers.EncodeVarint(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0x12
	}
	return len(dAtA) - i, nil
}

const maxUnmarshalDepth = 10000

func skipValue(dAtA []byte, wireType int, fieldNum int32) (int, error) {
	iNdEx := 0
	l := len(dAtA)
	switch wireType {
	case 0:
		for shift := 0; ; shift++ {
			if shift >= 10 {
				return 0, fmt.Errorf("invalid varint")
			}
			if iNdEx >= l {
				return 0, fmt.Errorf("invalid varint")
			}
			iNdEx++
			if dAtA[iNdEx-1] < 0x80 {
				break
			}
		}
	case 1:
		if (iNdEx + 8) > l {
			return 0, fmt.Errorf("truncated fixed64")
		}
		iNdEx += 8
	case 2:
		var length uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, fmt.Errorf("invalid bytes")
			}
			if iNdEx >= l {
				return 0, fmt.Errorf("invalid bytes")
			}
			b := dAtA[iNdEx]
			iNdEx++
			length |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		if int(length) < 0 {
			return 0, fmt.Errorf("invalid bytes")
		}
		iNdEx += int(length)
		if iNdEx < 0 || iNdEx > l {
			return 0, fmt.Errorf("invalid bytes")
		}
	case 3:
		_, n := protowire.ConsumeGroup(protowire.Number(fieldNum), dAtA[iNdEx:])
		if n < 0 {
			return 0, fmt.Errorf("invalid group")
		}
		iNdEx += n
	case 5:
		if (iNdEx + 4) > l {
			return 0, fmt.Errorf("truncated fixed32")
		}
		iNdEx += 4
	default:
		return 0, fmt.Errorf("unknown wire type %d", wireType)
	}
	return iNdEx, nil
}

func (m *TracesData) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *TracesData) unmarshal(dAtA []byte, depth int) error {
	if depth > maxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	if l >= 256 {
		var preIdx int
		var field1count int
		for preIdx < l {
			var preWire uint64
			for shift := uint(0); ; shift += 7 {
				if preIdx >= l {
					break
				}
				b := dAtA[preIdx]
				preIdx++
				preWire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			preNum := int32(preWire >> 3)
			preTyp := int(preWire & 0x7)
			switch preNum {
			case 1:
				field1count++
			}
			switch preTyp {
			case 0:
				for preIdx < l {
					preIdx++
					if dAtA[preIdx-1] < 0x80 {
						break
					}
				}
			case 1:
				preIdx += 8
			case 2:
				var preLen uint64
				for shift := uint(0); ; shift += 7 {
					if preIdx >= l {
						break
					}
					b := dAtA[preIdx]
					preIdx++
					preLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				preIdx += int(preLen)
			case 5:
				preIdx += 4
			default:
				break
			}
			if preIdx < 0 || preIdx > l {
				break
			}
		}
		if field1count > 0 {
			m.ResourceSpans = make([]ResourceSpans, 0, field1count)
		}
	}
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 35 {
				return fmt.Errorf("proto: integer overflow")
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // resource_spans
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intByteLen := int(byteLen)
			if intByteLen < 0 {
				return fmt.Errorf("proto: negative length")
			}
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ResourceSpans = append(m.ResourceSpans, ResourceSpans{})
			if err := m.ResourceSpans[len(m.ResourceSpans)-1].unmarshal(dAtA[iNdEx:postIndex], depth+1); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *ResourceSpans) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *ResourceSpans) unmarshal(dAtA []byte, depth int) error {
	if depth > maxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	if l >= 256 {
		var preIdx int
		var field2count int
		for preIdx < l {
			var preWire uint64
			for shift := uint(0); ; shift += 7 {
				if preIdx >= l {
					break
				}
				b := dAtA[preIdx]
				preIdx++
				preWire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			preNum := int32(preWire >> 3)
			preTyp := int(preWire & 0x7)
			switch preNum {
			case 2:
				field2count++
			}
			switch preTyp {
			case 0:
				for preIdx < l {
					preIdx++
					if dAtA[preIdx-1] < 0x80 {
						break
					}
				}
			case 1:
				preIdx += 8
			case 2:
				var preLen uint64
				for shift := uint(0); ; shift += 7 {
					if preIdx >= l {
						break
					}
					b := dAtA[preIdx]
					preIdx++
					preLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				preIdx += int(preLen)
			case 5:
				preIdx += 4
			default:
				break
			}
			if preIdx < 0 || preIdx > l {
				break
			}
		}
		if field2count > 0 {
			m.ScopeSpans = make([]ScopeSpans, 0, field2count)
		}
	}
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 35 {
				return fmt.Errorf("proto: integer overflow")
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // resource
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intByteLen := int(byteLen)
			if intByteLen < 0 {
				return fmt.Errorf("proto: negative length")
			}
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Resource.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			m.XXX_fieldsPresent[0] |= 1 << 0
		case 2: // scope_spans
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intByteLen := int(byteLen)
			if intByteLen < 0 {
				return fmt.Errorf("proto: negative length")
			}
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ScopeSpans = append(m.ScopeSpans, ScopeSpans{})
			if err := m.ScopeSpans[len(m.ScopeSpans)-1].unmarshal(dAtA[iNdEx:postIndex], depth+1); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3: // schema_url
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intByteLen := int(byteLen)
			if intByteLen < 0 {
				return fmt.Errorf("proto: negative length")
			}
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SchemaUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			m.XXX_fieldsPresent[0] |= 1 << 1
		default:
			n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *ScopeSpans) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *ScopeSpans) unmarshal(dAtA []byte, depth int) error {
	if depth > maxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	if l >= 256 {
		var preIdx int
		var field2count int
		for preIdx < l {
			var preWire uint64
			for shift := uint(0); ; shift += 7 {
				if preIdx >= l {
					break
				}
				b := dAtA[preIdx]
				preIdx++
				preWire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			preNum := int32(preWire >> 3)
			preTyp := int(preWire & 0x7)
			switch preNum {
			case 2:
				field2count++
			}
			switch preTyp {
			case 0:
				for preIdx < l {
					preIdx++
					if dAtA[preIdx-1] < 0x80 {
						break
					}
				}
			case 1:
				preIdx += 8
			case 2:
				var preLen uint64
				for shift := uint(0); ; shift += 7 {
					if preIdx >= l {
						break
					}
					b := dAtA[preIdx]
					preIdx++
					preLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				preIdx += int(preLen)
			case 5:
				preIdx += 4
			default:
				break
			}
			if preIdx < 0 || preIdx > l {
				break
			}
		}
		if field2count > 0 {
			m.Spans = make([]Span, 0, field2count)
		}
	}
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 35 {
				return fmt.Errorf("proto: integer overflow")
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // scope
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intByteLen := int(byteLen)
			if intByteLen < 0 {
				return fmt.Errorf("proto: negative length")
			}
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Scope.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
			m.XXX_fieldsPresent[0] |= 1 << 0
		case 2: // spans
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intByteLen := int(byteLen)
			if intByteLen < 0 {
				return fmt.Errorf("proto: negative length")
			}
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Spans = append(m.Spans, Span{})
			if err := m.Spans[len(m.Spans)-1].unmarshal(dAtA[iNdEx:postIndex], depth+1); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3: // schema_url
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intByteLen := int(byteLen)
			if intByteLen < 0 {
				return fmt.Errorf("proto: negative length")
			}
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SchemaUrl = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			m.XXX_fieldsPresent[0] |= 1 << 1
		default:
			n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *Span_Event) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *Span_Event) unmarshal(dAtA []byte, depth int) error {
	if depth > maxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	if l >= 256 {
		var preIdx int
		var field3count int
		for preIdx < l {
			var preWire uint64
			for shift := uint(0); ; shift += 7 {
				if preIdx >= l {
					break
				}
				b := dAtA[preIdx]
				preIdx++
				preWire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			preNum := int32(preWire >> 3)
			preTyp := int(preWire & 0x7)
			switch preNum {
			case 3:
				field3count++
			}
			switch preTyp {
			case 0:
				for preIdx < l {
					preIdx++
					if dAtA[preIdx-1] < 0x80 {
						break
					}
				}
			case 1:
				preIdx += 8
			case 2:
				var preLen uint64
				for shift := uint(0); ; shift += 7 {
					if preIdx >= l {
						break
					}
					b := dAtA[preIdx]
					preIdx++
					preLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				preIdx += int(preLen)
			case 5:
				preIdx += 4
			default:
				break
			}
			if preIdx < 0 || preIdx > l {
				break
			}
		}
		if field3count > 0 {
			m.Attributes = make([]commonv1.KeyValue, 0, field3count)
		}
	}
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 35 {
				return fmt.Errorf("proto: integer overflow")
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // time_unix_nano
			if wireType != 1 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v := binary.LittleEndian.Uint64(dAtA[iNdEx:])
			iNdEx += 8
			m.TimeUnixNano = v
			m.XXX_fieldsPresent[0] |= 1 << 0
		case 2: // name
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intByteLen := int(byteLen)
			if intByteLen < 0 {
				return fmt.Errorf("proto: negative length")
			}
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			m.XXX_fieldsPresent[0] |= 1 << 1
		case 3: // attributes
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intByteLen := int(byteLen)
			if intByteLen < 0 {
				return fmt.Errorf("proto: negative length")
			}
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attributes = append(m.Attributes, commonv1.KeyValue{})
			if err := m.Attributes[len(m.Attributes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4: // dropped_attributes_count
			if wireType != 0 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DroppedAttributesCount = uint32(v)
			m.XXX_fieldsPresent[0] |= 1 << 2
		default:
			n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *Span_Link) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *Span_Link) unmarshal(dAtA []byte, depth int) error {
	if depth > maxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	if l >= 256 {
		var preIdx int
		var field4count int
		for preIdx < l {
			var preWire uint64
			for shift := uint(0); ; shift += 7 {
				if preIdx >= l {
					break
				}
				b := dAtA[preIdx]
				preIdx++
				preWire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			preNum := int32(preWire >> 3)
			preTyp := int(preWire & 0x7)
			switch preNum {
			case 4:
				field4count++
			}
			switch preTyp {
			case 0:
				for preIdx < l {
					preIdx++
					if dAtA[preIdx-1] < 0x80 {
						break
					}
				}
			case 1:
				preIdx += 8
			case 2:
				var preLen uint64
				for shift := uint(0); ; shift += 7 {
					if preIdx >= l {
						break
					}
					b := dAtA[preIdx]
					preIdx++
					preLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				preIdx += int(preLen)
			case 5:
				preIdx += 4
			default:
				break
			}
			if preIdx < 0 || preIdx > l {
				break
			}
		}
		if field4count > 0 {
			m.Attributes = make([]commonv1.KeyValue, 0, field4count)
		}
	}
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 35 {
				return fmt.Errorf("proto: integer overflow")
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // trace_id
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intByteLen := int(byteLen)
			if intByteLen < 0 {
				return fmt.Errorf("proto: negative length")
			}
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TraceId = append(m.TraceId[:0], dAtA[iNdEx:postIndex]...)
			iNdEx = postIndex
			m.XXX_fieldsPresent[0] |= 1 << 0
		case 2: // span_id
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intByteLen := int(byteLen)
			if intByteLen < 0 {
				return fmt.Errorf("proto: negative length")
			}
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SpanId = append(m.SpanId[:0], dAtA[iNdEx:postIndex]...)
			iNdEx = postIndex
			m.XXX_fieldsPresent[0] |= 1 << 1
		case 3: // trace_state
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intByteLen := int(byteLen)
			if intByteLen < 0 {
				return fmt.Errorf("proto: negative length")
			}
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TraceState = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			m.XXX_fieldsPresent[0] |= 1 << 2
		case 4: // attributes
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intByteLen := int(byteLen)
			if intByteLen < 0 {
				return fmt.Errorf("proto: negative length")
			}
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attributes = append(m.Attributes, commonv1.KeyValue{})
			if err := m.Attributes[len(m.Attributes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5: // dropped_attributes_count
			if wireType != 0 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DroppedAttributesCount = uint32(v)
			m.XXX_fieldsPresent[0] |= 1 << 3
		case 6: // flags
			if wireType != 5 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v := binary.LittleEndian.Uint32(dAtA[iNdEx:])
			iNdEx += 4
			m.Flags = v
			m.XXX_fieldsPresent[0] |= 1 << 4
		default:
			n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *Span) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *Span) unmarshal(dAtA []byte, depth int) error {
	if depth > maxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	if l >= 256 {
		var preIdx int
		var field9count int
		var field11count int
		var field13count int
		for preIdx < l {
			var preWire uint64
			for shift := uint(0); ; shift += 7 {
				if preIdx >= l {
					break
				}
				b := dAtA[preIdx]
				preIdx++
				preWire |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			preNum := int32(preWire >> 3)
			preTyp := int(preWire & 0x7)
			switch preNum {
			case 9:
				field9count++
			case 11:
				field11count++
			case 13:
				field13count++
			}
			switch preTyp {
			case 0:
				for preIdx < l {
					preIdx++
					if dAtA[preIdx-1] < 0x80 {
						break
					}
				}
			case 1:
				preIdx += 8
			case 2:
				var preLen uint64
				for shift := uint(0); ; shift += 7 {
					if preIdx >= l {
						break
					}
					b := dAtA[preIdx]
					preIdx++
					preLen |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				preIdx += int(preLen)
			case 5:
				preIdx += 4
			default:
				break
			}
			if preIdx < 0 || preIdx > l {
				break
			}
		}
		if field9count > 0 {
			m.Attributes = make([]commonv1.KeyValue, 0, field9count)
		}
		if field11count > 0 {
			m.Events = make([]Span_Event, 0, field11count)
		}
		if field13count > 0 {
			m.Links = make([]Span_Link, 0, field13count)
		}
	}
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 35 {
				return fmt.Errorf("proto: integer overflow")
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 1: // trace_id
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intByteLen := int(byteLen)
			if intByteLen < 0 {
				return fmt.Errorf("proto: negative length")
			}
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TraceId = append(m.TraceId[:0], dAtA[iNdEx:postIndex]...)
			iNdEx = postIndex
			m.XXX_fieldsPresent[0] |= 1 << 0
		case 2: // span_id
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intByteLen := int(byteLen)
			if intByteLen < 0 {
				return fmt.Errorf("proto: negative length")
			}
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SpanId = append(m.SpanId[:0], dAtA[iNdEx:postIndex]...)
			iNdEx = postIndex
			m.XXX_fieldsPresent[0] |= 1 << 1
		case 3: // trace_state
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intByteLen := int(byteLen)
			if intByteLen < 0 {
				return fmt.Errorf("proto: negative length")
			}
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TraceState = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			m.XXX_fieldsPresent[0] |= 1 << 2
		case 4: // parent_span_id
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intByteLen := int(byteLen)
			if intByteLen < 0 {
				return fmt.Errorf("proto: negative length")
			}
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ParentSpanId = append(m.ParentSpanId[:0], dAtA[iNdEx:postIndex]...)
			iNdEx = postIndex
			m.XXX_fieldsPresent[0] |= 1 << 3
		case 16: // flags
			if wireType != 5 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			v := binary.LittleEndian.Uint32(dAtA[iNdEx:])
			iNdEx += 4
			m.Flags = v
			m.XXX_fieldsPresent[0] |= 1 << 4
		case 5: // name
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intByteLen := int(byteLen)
			if intByteLen < 0 {
				return fmt.Errorf("proto: negative length")
			}
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Name = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			m.XXX_fieldsPresent[0] |= 1 << 5
		case 6: // kind
			if wireType != 0 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Kind = Span_SpanKind(v)
			m.XXX_fieldsPresent[0] |= 1 << 6
		case 7: // start_time_unix_nano
			if wireType != 1 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v := binary.LittleEndian.Uint64(dAtA[iNdEx:])
			iNdEx += 8
			m.StartTimeUnixNano = v
			m.XXX_fieldsPresent[0] |= 1 << 7
		case 8: // end_time_unix_nano
			if wireType != 1 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			v := binary.LittleEndian.Uint64(dAtA[iNdEx:])
			iNdEx += 8
			m.EndTimeUnixNano = v
			m.XXX_fieldsPresent[0] |= 1 << 8
		case 9: // attributes
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intByteLen := int(byteLen)
			if intByteLen < 0 {
				return fmt.Errorf("proto: negative length")
			}
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attributes = append(m.Attributes, commonv1.KeyValue{})
			if err := m.Attributes[len(m.Attributes)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 10: // dropped_attributes_count
			if wireType != 0 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DroppedAttributesCount = uint32(v)
			m.XXX_fieldsPresent[0] |= 1 << 9
		case 11: // events
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intByteLen := int(byteLen)
			if intByteLen < 0 {
				return fmt.Errorf("proto: negative length")
			}
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Events = append(m.Events, Span_Event{})
			if err := m.Events[len(m.Events)-1].unmarshal(dAtA[iNdEx:postIndex], depth+1); err != nil {
				return err
			}
			iNdEx = postIndex
		case 12: // dropped_events_count
			if wireType != 0 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DroppedEventsCount = uint32(v)
			m.XXX_fieldsPresent[0] |= 1 << 10
		case 13: // links
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intByteLen := int(byteLen)
			if intByteLen < 0 {
				return fmt.Errorf("proto: negative length")
			}
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Links = append(m.Links, Span_Link{})
			if err := m.Links[len(m.Links)-1].unmarshal(dAtA[iNdEx:postIndex], depth+1); err != nil {
				return err
			}
			iNdEx = postIndex
		case 14: // dropped_links_count
			if wireType != 0 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.DroppedLinksCount = uint32(v)
			m.XXX_fieldsPresent[0] |= 1 << 11
		case 15: // status
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intByteLen := int(byteLen)
			if intByteLen < 0 {
				return fmt.Errorf("proto: negative length")
			}
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Status.unmarshal(dAtA[iNdEx:postIndex], depth+1); err != nil {
				return err
			}
			iNdEx = postIndex
			m.XXX_fieldsPresent[0] |= 1 << 12
		default:
			n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (m *Status) Unmarshal(b []byte) error {
	return m.unmarshal(b, 0)
}

func (m *Status) unmarshal(dAtA []byte, depth int) error {
	if depth > maxUnmarshalDepth {
		return fmt.Errorf("exceeded max recursion depth")
	}
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 35 {
				return fmt.Errorf("proto: integer overflow")
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		if wire>>3 < 1 || wire>>3 > 0x1FFFFFFF {
			return fmt.Errorf("invalid field number")
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		switch fieldNum {
		case 2: // message
			if wireType != 2 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var byteLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intByteLen := int(byteLen)
			if intByteLen < 0 {
				return fmt.Errorf("proto: negative length")
			}
			postIndex := iNdEx + intByteLen
			if postIndex < 0 {
				return fmt.Errorf("proto: negative length")
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
			m.XXX_fieldsPresent[0] |= 1 << 0
		case 3: // code
			if wireType != 0 {
				n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
				if err != nil {
					return err
				}
				iNdEx += n
				continue
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return fmt.Errorf("proto: integer overflow")
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Code = Status_StatusCode(v)
			m.XXX_fieldsPresent[0] |= 1 << 1
		default:
			n, err := skipValue(dAtA[iNdEx:], wireType, fieldNum)
			if err != nil {
				return err
			}
			iNdEx += n
		}
	}
	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}

func (this *TracesData) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*TracesData)
	if !ok {
		that2, ok := that.(TracesData)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if len(this.ResourceSpans) != len(that1.ResourceSpans) {
		return false
	}
	for i := range this.ResourceSpans {
		if !this.ResourceSpans[i].Equal(that1.ResourceSpans[i]) {
			return false
		}
	}
	return true
}

func (this *ResourceSpans) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ResourceSpans)
	if !ok {
		that2, ok := that.(ResourceSpans)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Resource.Equal(that1.Resource) {
		return false
	}
	if len(this.ScopeSpans) != len(that1.ScopeSpans) {
		return false
	}
	for i := range this.ScopeSpans {
		if !this.ScopeSpans[i].Equal(that1.ScopeSpans[i]) {
			return false
		}
	}
	if this.SchemaUrl != that1.SchemaUrl {
		return false
	}
	return true
}

func (this *ScopeSpans) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*ScopeSpans)
	if !ok {
		that2, ok := that.(ScopeSpans)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !this.Scope.Equal(that1.Scope) {
		return false
	}
	if len(this.Spans) != len(that1.Spans) {
		return false
	}
	for i := range this.Spans {
		if !this.Spans[i].Equal(that1.Spans[i]) {
			return false
		}
	}
	if this.SchemaUrl != that1.SchemaUrl {
		return false
	}
	return true
}

func (this *Span_Event) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Span_Event)
	if !ok {
		that2, ok := that.(Span_Event)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.TimeUnixNano != that1.TimeUnixNano {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if len(this.Attributes) != len(that1.Attributes) {
		return false
	}
	for i := range this.Attributes {
		if !this.Attributes[i].Equal(that1.Attributes[i]) {
			return false
		}
	}
	if this.DroppedAttributesCount != that1.DroppedAttributesCount {
		return false
	}
	return true
}

func (this *Span_Link) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Span_Link)
	if !ok {
		that2, ok := that.(Span_Link)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.TraceId, that1.TraceId) {
		return false
	}
	if !bytes.Equal(this.SpanId, that1.SpanId) {
		return false
	}
	if this.TraceState != that1.TraceState {
		return false
	}
	if len(this.Attributes) != len(that1.Attributes) {
		return false
	}
	for i := range this.Attributes {
		if !this.Attributes[i].Equal(that1.Attributes[i]) {
			return false
		}
	}
	if this.DroppedAttributesCount != that1.DroppedAttributesCount {
		return false
	}
	if this.Flags != that1.Flags {
		return false
	}
	return true
}

func (this *Span) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Span)
	if !ok {
		that2, ok := that.(Span)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.TraceId, that1.TraceId) {
		return false
	}
	if !bytes.Equal(this.SpanId, that1.SpanId) {
		return false
	}
	if this.TraceState != that1.TraceState {
		return false
	}
	if !bytes.Equal(this.ParentSpanId, that1.ParentSpanId) {
		return false
	}
	if this.Flags != that1.Flags {
		return false
	}
	if this.Name != that1.Name {
		return false
	}
	if this.Kind != that1.Kind {
		return false
	}
	if this.StartTimeUnixNano != that1.StartTimeUnixNano {
		return false
	}
	if this.EndTimeUnixNano != that1.EndTimeUnixNano {
		return false
	}
	if len(this.Attributes) != len(that1.Attributes) {
		return false
	}
	for i := range this.Attributes {
		if !this.Attributes[i].Equal(that1.Attributes[i]) {
			return false
		}
	}
	if this.DroppedAttributesCount != that1.DroppedAttributesCount {
		return false
	}
	if len(this.Events) != len(that1.Events) {
		return false
	}
	for i := range this.Events {
		if !this.Events[i].Equal(that1.Events[i]) {
			return false
		}
	}
	if this.DroppedEventsCount != that1.DroppedEventsCount {
		return false
	}
	if len(this.Links) != len(that1.Links) {
		return false
	}
	for i := range this.Links {
		if !this.Links[i].Equal(that1.Links[i]) {
			return false
		}
	}
	if this.DroppedLinksCount != that1.DroppedLinksCount {
		return false
	}
	if !this.Status.Equal(that1.Status) {
		return false
	}
	return true
}

func (this *Status) Equal(that interface{}) bool {
	if that == nil {
		return this == nil
	}

	that1, ok := that.(*Status)
	if !ok {
		that2, ok := that.(Status)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		return this == nil
	} else if this == nil {
		return false
	}
	if this.Message != that1.Message {
		return false
	}
	if this.Code != that1.Code {
		return false
	}
	return true
}

func (m *TracesData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *TracesData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

func (m *TracesData) XXX_Merge(src proto.Message) {
	if s, ok := src.(*TracesData); ok {
		b, err := s.Marshal()
		if err != nil {
			return
		}
		_ = m.Unmarshal(b)
	}
}

func (m *TracesData) XXX_Size() int {
	return m.Size()
}

func (m *TracesData) XXX_DiscardUnknown() {}

func (m *TracesData) XXX_MessageName() string {
	return "tempopb.trace.v1.TracesData"
}

func (m *ResourceSpans) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *ResourceSpans) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

func (m *ResourceSpans) XXX_Merge(src proto.Message) {
	if s, ok := src.(*ResourceSpans); ok {
		b, err := s.Marshal()
		if err != nil {
			return
		}
		_ = m.Unmarshal(b)
	}
}

func (m *ResourceSpans) XXX_Size() int {
	return m.Size()
}

func (m *ResourceSpans) XXX_DiscardUnknown() {}

func (m *ResourceSpans) XXX_MessageName() string {
	return "tempopb.trace.v1.ResourceSpans"
}

func (m *ScopeSpans) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *ScopeSpans) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

func (m *ScopeSpans) XXX_Merge(src proto.Message) {
	if s, ok := src.(*ScopeSpans); ok {
		b, err := s.Marshal()
		if err != nil {
			return
		}
		_ = m.Unmarshal(b)
	}
}

func (m *ScopeSpans) XXX_Size() int {
	return m.Size()
}

func (m *ScopeSpans) XXX_DiscardUnknown() {}

func (m *ScopeSpans) XXX_MessageName() string {
	return "tempopb.trace.v1.ScopeSpans"
}

func (m *Span_Event) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *Span_Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

func (m *Span_Event) XXX_Merge(src proto.Message) {
	if s, ok := src.(*Span_Event); ok {
		b, err := s.Marshal()
		if err != nil {
			return
		}
		_ = m.Unmarshal(b)
	}
}

func (m *Span_Event) XXX_Size() int {
	return m.Size()
}

func (m *Span_Event) XXX_DiscardUnknown() {}

func (m *Span_Event) XXX_MessageName() string {
	return "tempopb.trace.v1.Span.Event"
}

func (m *Span_Link) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *Span_Link) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

func (m *Span_Link) XXX_Merge(src proto.Message) {
	if s, ok := src.(*Span_Link); ok {
		b, err := s.Marshal()
		if err != nil {
			return
		}
		_ = m.Unmarshal(b)
	}
}

func (m *Span_Link) XXX_Size() int {
	return m.Size()
}

func (m *Span_Link) XXX_DiscardUnknown() {}

func (m *Span_Link) XXX_MessageName() string {
	return "tempopb.trace.v1.Span.Link"
}

func (m *Span) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *Span) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

func (m *Span) XXX_Merge(src proto.Message) {
	if s, ok := src.(*Span); ok {
		b, err := s.Marshal()
		if err != nil {
			return
		}
		_ = m.Unmarshal(b)
	}
}

func (m *Span) XXX_Size() int {
	return m.Size()
}

func (m *Span) XXX_DiscardUnknown() {}

func (m *Span) XXX_MessageName() string {
	return "tempopb.trace.v1.Span"
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}

func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	b = b[:cap(b)]
	n, err := m.MarshalToSizedBuffer(b)
	if err != nil {
		return nil, err
	}
	return b[:n], nil
}

func (m *Status) XXX_Merge(src proto.Message) {
	if s, ok := src.(*Status); ok {
		b, err := s.Marshal()
		if err != nil {
			return
		}
		_ = m.Unmarshal(b)
	}
}

func (m *Status) XXX_Size() int {
	return m.Size()
}

func (m *Status) XXX_DiscardUnknown() {}

func (m *Status) XXX_MessageName() string {
	return "tempopb.trace.v1.Status"
}

func init() {
	protohelpers.RegisterEnum("tempopb.trace.v1.SpanFlags", SpanFlags_name, SpanFlags_value)
	protohelpers.RegisterType((*TracesData)(nil), "tempopb.trace.v1.TracesData")
	protohelpers.RegisterType((*ResourceSpans)(nil), "tempopb.trace.v1.ResourceSpans")
	protohelpers.RegisterType((*ScopeSpans)(nil), "tempopb.trace.v1.ScopeSpans")
	protohelpers.RegisterType((*Span_Event)(nil), "tempopb.trace.v1.Span.Event")
	protohelpers.RegisterType((*Span_Link)(nil), "tempopb.trace.v1.Span.Link")
	protohelpers.RegisterEnum("tempopb.trace.v1.Span.SpanKind", Span_SpanKind_name, Span_SpanKind_value)
	protohelpers.RegisterType((*Span)(nil), "tempopb.trace.v1.Span")
	protohelpers.RegisterEnum("tempopb.trace.v1.Status.StatusCode", Status_StatusCode_name, Status_StatusCode_value)
	protohelpers.RegisterType((*Status)(nil), "tempopb.trace.v1.Status")
}
